from django.urls import path
from . import api_v2, frontend_compat

urlpatterns = [
    path("health/", api_v2.health),
    path("bootstrap/", frontend_compat.bootstrap),
    path("auth/register/", api_v2.register_api),
    path("auth/login/", api_v2.login_api),
    path("auth/logout/", api_v2.logout_api),
    path("listings/", api_v2.listings_api),
    path("listings/<slug:slug>/", api_v2.listing_detail_api),
    path("listings/<slug:slug>/availability/", api_v2.availability_api),
    path("listings/<slug:slug>/reviews/", api_v2.reviews_api),
    path("availability/<int:slot_id>/", api_v2.availability_delete_api),
    path("favorites/<slug:slug>/", api_v2.favorite_api),
    path("match/", api_v2.smart_match_api),
    path("sessions/", api_v2.sessions_api),
    path("sessions/<uuid:session_id>/", api_v2.session_detail_api),
    path("sessions/<uuid:session_id>/cancel/", api_v2.cancel_session_api),
    path("sessions/<uuid:session_id>/files/", api_v2.session_file_api),
    path("tasks/<int:task_id>/", api_v2.task_api),
    path("bookings/", api_v2.bookings_api),
    path("bookings/<uuid:booking_id>/", api_v2.booking_detail_api),
    path("conversations/", api_v2.conversations_api),
    path("conversations/listing/<slug:slug>/", api_v2.conversation_for_listing_api),
    path("conversations/<uuid:conversation_id>/", api_v2.conversation_api),
    path("notifications/", api_v2.notifications_api),
    path("provider/dashboard/", api_v2.provider_dashboard_api),
    path("provider/listings/", api_v2.provider_listings_api),
    path("provider/listings/<slug:slug>/", api_v2.provider_listing_detail_api),
]
